../rtl/dut.v
../src/inc.svh
../src/my_if.sv
../src/my_transaction.sv
../src/my_sequencer.sv
../src/my_driver.sv
../src/my_monitor.sv
../src/my_agent.sv
../src/my_scoreboard.sv
../src/my_model.sv
../src/my_env.sv
../src/base_test.sv
../src/my_case0.sv
../src/my_case1.sv
../src/top_tb.sv